### ISSUE TITLE
Error: file_get_contents(/var/www/nextcloud/apps/onlyoffice/assets/en-US/new.md): Failed to open stream: No such file or directory at /var/www/nextcloud/apps/onlyoffice/lib/templatemanager.php#201

### ISSUE THREAD

**Issue by andyxheli** [ONLYOFFICE/onlyoffice-nextcloud#492]
Getting the below error after creating New text document files  Nextcloud 21.0.2  PHP8
```
{"reqId":"ztKZBUuNrprP9OXWBsaZ","level":3,"time":"2021-06-25T14:10:40+00:00","remoteAddr":"66.58.34.84","user":"admin","app":"PHP","method":"POST","url":"/ocs/v2.php/apps/files/api/v1/templates/create","message":{"Exception":"Error","Message":"file_get_contents(/var/www/nextcloud/apps/onlyoffice/assets/en-US/new.md): Failed to open stream: No such file or directory at /var/www/nextcloud/apps/onlyoffice/lib/templatemanager.php#201","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/onlyoffice/lib/templatemanager.php","line":201,"function":"file_get_contents"},{"file":"/var/www/nextcloud/apps/onlyoffice/appinfo/application.php","line":239,"function":"GetEmptyTemplate","class":"OCA\\Onlyoffice\\TemplateManager","type":"::"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"OCA\\Onlyoffice\\AppInfo\\{closure}","class":"OCA\\Onlyoffice\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":98,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Template/TemplateManager.php","line":175,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/TemplateController.php","line":56,"function":"createFromTemplate","class":"OC\\Files\\Template\\TemplateManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"create","class":"OCA\\Files\\Controller\\TemplateController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","version":"21.0.2.1","id":"60d5e46bd0557"}
```

**Comment by LinneyS** [comment]
Hi @andyxheli 
Do you upload submodule ?
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/.gitmodules

**Comment by andyxheli** [comment]
Hi @LinneyS 

I don't think so. Maybe, how do I add the submodule or where do I check that I have it ?

**Comment by SergeyKorneyev** [comment]
Hi @andyxheli 
You just need to `cd` to the ONLYOFFICE connector folder on your Nextcloud server (it's usually located in [your-nextcloud-directory]/apps/onlyoffice/) and execute the `git submodule update --init --recursive` command.

**Comment by andyxheli** [comment]
@SergeyKorneyev Please see below error 

![image](https://user-images.githubusercontent.com/59488153/123648274-6f094980-d7ee-11eb-8995-db40b09c4d14.png)

**Comment by SergeyKorneyev** [comment]
In that case, please try downloading the following files and placing them in the /var/www/nextcloud/apps/onlyoffice/assets/ folder: https://github.com/ONLYOFFICE/document-templates/tree/main/new

**Comment by andyxheli** [comment]
@SergeyKorneyev the 3 files are there but im not creating any those files extinction im creating .txt, .md so im not sure why onlyoffice is throwing an error

**Comment by IXALB** [comment]
Same issue here also

**Comment by LinneyS** [comment]
We understand your problem
Fixed
Thank you

**Comment by andyxheli** [comment]
@LinneyS thank you!

**Comment by andyxheli** [comment]
> We understand your problem
> Fixed
> Thank you

Looks good tested the fix on my server.

**Comment by andyxheli** [comment]
@LinneyS Do you know when this fix will be pushed ? Still an issue on V7.0.2

**Comment by andyxheli** [comment]
Still an issue need to be applied
